package Server;

public enum DataType {

    CONNECT,CONNECT_SUCCESS, CONNECT_BAD, PING, ROOM_CREATE, ROOM_JOIN, LOBBY_CHAT, DISCONNECT, REGISTER_USER, REGISTER_USER_SUCCESS, REGISTER_USER_FAIL, LOGIN_USER, LOGIN_USER_SUCCESS, LOGIN_USER_FAIL
}
